<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>BardQuest.Mod</AssemblyName>
    <Nullable>disable</Nullable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <Import Project="Refs.props" />
  <ItemGroup>
    <ProjectReference Include="../../src/BardQuest.Domain/BardQuest.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyMetadata Condition="'$(ModVersion)' != ''" Include="BardQuestModVersion" Value="$(ModVersion)" />
    <AssemblyMetadata Include="BardQuestYargTarget" Value="$(YargTarget)" />
  </ItemGroup>
</Project>
